{% set name = "ksops" %}
{% set version = "4.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/viaduct-ai/kustomize-sops/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 850923bed7b34b76eda237b6dd57d744f96ae8a5d2e871eb5a6dac6b220dec09
  folder: src

build:
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses
    - go build -v -o $PREFIX/bin/ksops  # [not win]
    - go build -v -o %LIBRARY_BIN%\ksops.exe  # [win]
    # Clear out cache to avoid file not removable warnings
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)  # [unix]
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - test -f $PREFIX/bin/ksops  # [not win]
    - test -f %LIBRARY_BIN%\ksops.exe  # [win]

about:
  home: https://github.com/viaduct-ai/kustomize-sops
  summary: A Flexible Kustomize Plugin for SOPS Encrypted Resources
  license: Apache-2.0
  license_family: Apache
  license_file:
    - src/LICENSE
    - library_licenses/
  dev_url: https://github.com/viaduct-ai/kustomize-sops

extra:
  recipe-maintainers:
    - pavelzw
    - ytausch
